Kingdoms:
  Dracosis:
    Tax: 2 # in percents
    Castle:
      x: 0
      y: 0
      z: 0
      level: world
    Village:
      x: 0
      y: 0
      z: 0
      level: world
  Quay:
    Tax: 2
    Castle:
      x: 0
      y: 0
      z: 0
      level: world
    Village:
      x: 0
      y: 0
      z: 0
      level: world
  Cordian:
    Tax: 2
    Castle:
      x: 0
      y: 0
      z: 0
      level: world
    Village:
      x: 0
      y: 0
      z: 0
      level: world
Power-Areas:
- x1: 0
  x2: 0
  z1: 0
  z2: 0
  level: world
- x1: 0
  x2: 0
  z1: 0
  z2: 0
  level: world
- x1: 0
  x2: 0
  z1: 0
  z2: 0
  level: world
- x1: 0
  x2: 0
  z1: 0
  z2: 0
  level: world