Kingdoms:
  Dracosis:
    Castle:
      x: 0
      "y": 100
      z: 0
      level: world
    Village:
      x: 0
      "y": 100
      z: 0
      level: world
  Quay:
    Castle:
      x: 0
      "y": 100
      z: 0
      level: world
    Village:
      x: 0
      "y": 100
      z: 0
      level: world
  Cordian:
    Castle:
      x: 0
      "y": 100
      z: 0
      level: world
    Village:
      x: 0
      "y": 100
      z: 0
      level: world
Taxes: # Taxes are percentage values out of 100
  Dracosis: 2
  Quay: 2
  Cordian: 2
Leaders:
  Dracosis: "David2020xD"
  Quay: "xXDismalAngelXx"
  Cordian: "MistCraftPlays"
Power:
  Dracosis: 0
  Quay: 0
  Cordian: 0
Power-Areas:
  Areas:
  - x1: 0
    x2: 0
    z1: 0
    z2: 0
    level: world
  - x1: 0
    x2: 0
    z1: 0
    z2: 0
    level: world
  - x1: 0
    x2: 0
    z1: 0
    z2: 0
    level: world
  - x1: 0
    x2: 0
    z1: 0
    z2: 0
    level: world
  Time-Per-Power: 2 # minutes per set power given to kingdom
  Power-Per-Time: 2 # Power given every set amount of time