Kingdoms:
  Dracosis:
    Castle:
      x: 0
      y: 0
      z: 0
      level: world
    Village:
      x: 0
      y: 0
      z: 0
      level: world
  Quay:
    Castle:
      x: 0
      y: 0
      z: 0
      level: world
    Village:
      x: 0
      y: 0
      z: 0
      level: world
  Cordian:
    Castle:
      x: 0
      y: 0
      z: 0
      level: world
    Village:
      x: 0
      y: 0
      z: 0
      level: world