# The time before the rank is removed from the player in hours
RankTimeout: 24
Ranks:
  Knight:
    Description: ""
    Chat: "&3&l{prefix}&e[{rank}]&f&r {display_name} &7> {msg}"
    Image-Link: ""
    Effects:
     - "speed 1 5"
     - ""
    Items:
     - "diamond_helmet 1 {ench:[{id:0s,lvl:2s}]}"
     - ""
  Farmer:
    Description: ""
    Chat: "&3&l{prefix}&e[{rank}]&f&r {display_name} &7> {msg}"
    Image-Link: ""
    Effects:
     - ""
     - ""
    Items:
     - ""
     - ""
  Gladiator:
    Description: ""
    Chat: "&3&l{prefix}&e[{rank}]&f&r {display_name} &7> {msg}"
    Image-Link: ""
    Effects:
     - ""
     - ""
    Items:
     - ""
     - ""
  Horseback:
    Description: ""
    Chat: "&3&l{prefix}&e[{rank}]&f&r {display_name} &7> {msg}"
    Image-Link: ""
    Effects:
     - ""
     - ""
    Items:
     - ""
     - ""
  Mage:
    Description: ""
    Chat: "&3&l{prefix}&e[{rank}]&f&r {display_name} &7> {msg}"
    Image-Link: ""
    Effects:
     - ""
     - ""
    Items:
     - ""
     - ""