name: KingdomCore
author: kaliiks
version: 1.0
api: [3.0.0-ALPHA9, 3.0.0-ALPHA8]
load: STARTUP
main: KingdomCore\Main

commands:
   k:
    description: Make you able to join kingdom
   warpme:
    description: Warp cmd
   money:
    description: Money cmd
   vote:
    description: Vote cmd